title: Syntax-Highlighting from a Markdown source using Go 
short: "This post shows one way to create syntax-highlighted HTML from a markdown source. Using only Go."
date: 09.06.2017
tags:
    - golang
    - go
    - syntax-highlighting
    - markdown
