title: Getting Started with Smart Contracts using Solidity 
short: "Smart Contracts and Blockchain Technology are quite intriguing topics. This post shows an example for a Winner Takes All Crowdfunding contract implemented with Solidity."
date: 06.02.2017
tags:
    - blockchain
    - ethereum
    - smartcontracts 
    - solidity
    - crowdfunding
