title: Getting Started with Ethereum Smart Contracts using Solidity 
short: "Smart Contracts and Blockchain Technology are quite intriguing. This post shows an example for a Winner Takes All Crowdfunding contract implemented with Solidity."
date: 23.01.2017
tags:
    - blockchain
    - ethereum
    - smartcontracts 
    - solidity
    - crowdfunding
