title: Using Teaching for Deepening Your Own Knowledge
short: "This post is my take on how I have used teaching as a tool for improving and deepening my own knowledge on several topics."
date: 03.10.2019
tags:
    - learning
    - knowledge
    - teaching
