title: Some Practical Advice for User Group Organizers
short: "User Groups or Meetups are a great way to stay in touch with the local tech scene. Organizing such a meetup can also be a very rewarding experience, especially if done right and with a vibrant community to back you up."
date: 20.12.2016
tags:
    - Usergroup
    - Community
    - Talks
    - OpenSpace
    - Organization
