title: No Ads, No Tracking, One Roundtrip
short: "In this post we'll look at the rationale behind making this blog as fast and lightweight as it is and why there are no trackers and/or ads present and why they never will be."
date: 20.12.2019
tags:
    - ads
    - performance
    - tracking
    - blog
