title: The Tale of the Missing Read Handler in Go
short: "This is the story of a bug hunt featuring Gorilla WebSockets, Go and a confused programmer (me) :)"
date: 06.08.2019
tags:
    - Go
    - WebSockets
    - Gorilla
    - Bug
