title: Review of Craft Conf 2017 
short: "Craft Conf has been one of the best tech conferences I've been to and continues to deliver."
date: 30.04.2017
tags:
    - conference
    - craftconf
    - craft
    - review
