title: Interacting with Ethereum Smart Contracts using Go 
short: "Smart Contracts and Blockchain remain a hot topic. This post will show how to interact with Ethereum Smart Contracts using Go. "
date: 23.07.2017
tags:
    - Go
    - Golang
    - ethereum 
    - blockchain 
    - smartcontracts 
