title: The Benefits of Uninterrupted, Focused Work 
short: "Since my transition to being self-employed, I have been working from home. This post outlines some of the learnings I made over the last months in terms of increasing my productivity in a sustainable, healthy way."
date: 21.08.2017
tags:
    - focus
    - work
    - process
    - pomodoro
    - health
    - exercise
