title: Port Forwarding with Go 
short: "In this post, I take a look at how simple it is to do port forwarding with Go's great standard library."
date: 18.03.2017
tags:
    - Go
    - Golang
    - network 
    - forwarding
    - tunnelling
