title: Asyncifying an Actix Web App and Upgrading it to 1.0
short: "In a previous post, we created an Actix 0.7 Web App, which was not fully non-blocking. In this post, we'll become fully non-blocking and upgrade the app to Actix 1.0"
date: 20.06.2019
tags:
    - Rust
    - Actix
    - Futures
    - Async
