title: Synchronized Asynchronous Job Runner in Rust 
short: "In this post we'll implement a basic asynchronous job runner, which synchronizes job runs among several clients using Redis."
date: 15.01.2020
tags:
    - Rust
    - Async
    - job
    - runner
