title: Elasticsearch to Prometheus Exporter in Go 
short: "This post describes how to create a server in Go, which provides data from Elasticsearch for Prometheus to consume."
date: 05.07.2018
tags:
    - Go
    - Golang
    - elasticsearch
    - prometheus
    - ops
